config/routes.rb
Blog::Application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'stories#index'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/writestory', to: 'stories#new', via: 'get'

  resources :stories do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post 
	validates_presence_of :story_id
	validates_presence_of :body
end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy 
	validates :title, presence: true
	validates :content, presence: true
	validates :user_id, presence: true
	default_scope -> { order('created_at DESC') }

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
				uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }
	has_secure_password

	has_many :comments, dependent: :destroy
	has_many :stories, dependent: :destroy

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @story = Story.find(params[:story_id])
    @comment = @story.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @story, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:story_id, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
    	if user && user.authenticate(params[:session][:password])
     		sign_in user
      		redirect_to user
    	else
      		flash.now[:error] = 'Invalid email/password combination'
      		render 'new'
    	end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def contact
  end

  def about
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_action :signed_in_user, only: [:new, :create, :update, :destroy]

	def index
		@story = Story.all
	end

	def show
		@story = Story.find(params[:id])
	end

	def new
		@story = Story.new
	end

	def create
		@story = current_user.stories.build(story_params)
		if @story.save
			flash[:success] = "Story Posted!"
			redirect_to @story
		else
			render 'new'
		end

	end

	def edit
		@story = Story.find(params[:id])
	end

	def update
	end

	def destroy
		@story = Story.find(params[:id])
		@story.destroy
		flash[:success] = "Story deleted."
		redirect_to user_path(@story.user)
	end

	private

		def story_params
			params.require(:story).permit(:title, :content)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
      flash[:success] = 'Welcome!'
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
    @stories = @user.stories.paginate(page: params[:page])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  	def signed_in?
  		!current_user.nil?
  	end

  	def sign_out
  		current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    	cookies.delete(:remember_token)
    	self.current_user = nil
  	end

  	def current_user=(user)
  		@current_user = user
  	end

  	def current_user
    	remember_token = User.digest(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
  	end

    def current_user?(user)
      user == current_user
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<p>
		<strong>Posted <%= time_ago_in_words(comment.created_at) %></strong>
		<br />
		<%= h(comment.body) %>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :story_id %><br>
    <%= f.number_field :story_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(partial: @comment))%>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.story_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.story_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div>
	<% if signed_in? %>
		<%= link_to "Sign out", signout_path, method: "delete" %>
	<% end %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/stories/_comment.html.erb
<%= div_for comment do %>
	<p>
		<strong>Posted <%= time_ago_in_words(comment.created_at) %></strong>
		<br />
		<%= h(comment.body) %>
	</p>
<% end %>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.bootsy_area :content, class: 'form-control', rows: 12 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/_story.html.erb
<li>
	<%= link_to story.title, story %>
	Posted <%= time_ago_in_words(story.created_at) %> ago.
</li>

app/views/stories/edit.html.erb
<h1>Edit your story</h1>

app/views/stories/index.html.erb
<h1>Front Page</h1>

app/views/stories/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>New post</h1>
	<%= render 'form' %>
</div>
<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<h3><%= @story.title %></h3>
<strong><%= link_to @story.user.name, @story.user %></strong>
 - <%= time_ago_in_words(@story.created_at) %> ago.
 <div>
 	<%= link_to 'Edit', edit_story_path %>
 	 | 
 	<%= link_to 'Delete', @story, method: :delete,
 								 data: { confirm: "Are you sure?" } %>
 </div>
<p><%= raw @story.content %></p>

<h3>Comments</h3>
<div id="comments">
	<%= render :partial => @story.comments %>
</div>

<%= form_for [@story, Comment.new] do |f| %>
	<p>
		<%= f.label :body, "New Comment" %><br />
		<%= f.text_area :body %>
	</p>
	<p><%= f.submit "Add Comment" %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div>
  <div>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>
<div><%= link_to "New Story", writestory_path %></div>
<div id="stories-list">
	<% if @user.stories.any? %>	
		<h3>Stories</h3>
		<ul>
			<%= render @stories %>
		</ul>
		<%= will_paginate @stories %>
	<% end %>
	
</div>